# Generated by Django 3.0.3 on 2020-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='num_donors',
        ),
        migrations.AddField(
            model_name='donation',
            name='total_donated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
